### Signup
POST http://localhost:3696/users/signup
content-type: application/json

{
  "email" : "new2@mail.com",
  "password": "123",
  "name": "not need"
}

### Login
POST http://localhost:3696/users/signin
content-type: application/json

{
  "email" : "new@mail.com",
  "password": "123"
}

### whoami
GET http://localhost:3696/users/whoami

# ===========================================================

### Demo Save-session
GET http://localhost:3696/demos/save-session

### Demo Get-session
GET http://localhost:3696/demos/get-session

# ===========================================================

### get user by id
GET http://localhost:3696/users/3

### get user by email query
GET http://localhost:3696/users?email=demo-0618@mai.com

### delete user by id
DELETE http://localhost:3696/users/1

### update user by id
PATCH http://localhost:3696/users/4
content-type: application/json

{
  "password": "new"
}